import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/components/client-view/common-layout";
import CanvasCursor from "@/cursify/CanvasCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Suraj Barnwal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: "radial-gradient(#00c850 1px, smokewhite 1px)",
          backgroundSize: "20px 20px",
          minHeight: "100vh",
        }}
      >
        <CanvasCursor />
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
